parser: babel-eslint
env:
  node: true
  mocha: true
extends: airbnb-base
sourceType: module
plugins:
  - import
rules:
  global-require: 0
  quote-props: 0
  strict: 0
  no-continue: 0
  no-param-reassign: 0
  consistent-return: 0
  no-unused-vars: 1
  max-len: 0
  comma-dangle: 0
  no-underscore-dangle: 0
  generator-star-spacing: 0
  camelcase: 0
  import/no-dynamic-require: 0
  no-shadow: 0